name: Java Maven Build

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  pull_request:
    branches:
      - main  # Runs when a pull request is made to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub's Ubuntu runner

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK 22
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'  # You can change the version here if needed
        distribution: 'temurin'  # Use 'temurin' as the JDK distribution

    # Step 3: Build with Maven
    - name: Build with Maven
      run: mvn clean install  # Runs Maven's clean install command
