name: Java Maven Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (JDK 22, using temurin)
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'  # Specify your desired JDK version
        distribution: 'temurin'  # Use 'temurin' instead of 'adoptopenjdk'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3  # Updated to v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 5: Run tests with Maven
    - name: Run tests with Maven
      run: mvn test

    # Optional: Upload artifacts (if needed)
    # - name: Upload build artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: build-artifacts
    #     path: target/*.jar
